{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "7.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.2.2.jar",
          "url": "gradle-api-7.2.2.jar",
          "size": 237984,
          "sha512": "419f3a9a5dceb8e071cd4afbf18ee4b0121145d9e265a86a970a5c505eaa27644cb4d680f3a9d77ec4c547c668ce62107f2bfd25c21ba2e3c4bfc9106b6bd011",
          "sha256": "94e5b786e74e731a23d221f109292a9dcbf3d8ca5d4a7cf2065b418759ae110d",
          "sha1": "ff773057b490c477db4e46adb8f002dff1bf0c9f",
          "md5": "ff43e213cfd1d72fb8d268d6331ca8c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.2.2.jar",
          "url": "gradle-api-7.2.2.jar",
          "size": 237984,
          "sha512": "419f3a9a5dceb8e071cd4afbf18ee4b0121145d9e265a86a970a5c505eaa27644cb4d680f3a9d77ec4c547c668ce62107f2bfd25c21ba2e3c4bfc9106b6bd011",
          "sha256": "94e5b786e74e731a23d221f109292a9dcbf3d8ca5d4a7cf2065b418759ae110d",
          "sha1": "ff773057b490c477db4e46adb8f002dff1bf0c9f",
          "md5": "ff43e213cfd1d72fb8d268d6331ca8c6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.2.2-javadoc.jar",
          "url": "gradle-api-7.2.2-javadoc.jar",
          "size": 465134,
          "sha512": "ccef9588ce858d3b002d54f0183b96790cb85c6d84e014d73bc4328c6e809f00322457dd47dba881e127866091c20056ce6a682c9aec2c0a0aff25a31dc155c8",
          "sha256": "aa3004823a4c01f25a93583804ef1a91edb4cdb676422a86b59bec83f7ec2f98",
          "sha1": "97ba2b32e8819e9a734f43b42795e4e2b0736956",
          "md5": "68fd3e4ffbf81562612e006d84047459"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.2.2-sources.jar",
          "url": "gradle-api-7.2.2-sources.jar",
          "size": 242051,
          "sha512": "08fd62f2ff202b9f58aec8fc057eedf3ad408cacdd45ea10e743af67559316b31ba0433793ca5881a1bb26c5464a3ad2c042ba006a8c4d1b06c56b0ad1e4e269",
          "sha256": "7502f920bae19768e4ce82b461a437c6a2e707fbdd29e2fb5bab4fabb6a66bb7",
          "sha1": "f59efb3221ca3d2628b610445fca1f7e66793162",
          "md5": "0bb5aa2f0806426242e45dac86ba9a46"
        }
      ]
    }
  ]
}
