{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.analytics-library",
    "module": "protos",
    "version": "30.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "protos-30.1.1.jar",
          "url": "protos-30.1.1.jar",
          "size": 5183836,
          "sha512": "d4df833f1a5bf9b70597c003ece7d2e40f7bcb01cedd5973941c5bdddabc74db0cf5d1133877488193e1f145c1fca36e03289d5409102d3f281e4c10696df0a6",
          "sha256": "83bd75a36ca159179f234b46c9537fb669cbff45153582109891949cbd842a35",
          "sha1": "a8eee5e72201792e52c53b1196dbdfecbc20dc7b",
          "md5": "2479947d0a9690d954666af96171375c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "protos-30.1.1.jar",
          "url": "protos-30.1.1.jar",
          "size": 5183836,
          "sha512": "d4df833f1a5bf9b70597c003ece7d2e40f7bcb01cedd5973941c5bdddabc74db0cf5d1133877488193e1f145c1fca36e03289d5409102d3f281e4c10696df0a6",
          "sha256": "83bd75a36ca159179f234b46c9537fb669cbff45153582109891949cbd842a35",
          "sha1": "a8eee5e72201792e52c53b1196dbdfecbc20dc7b",
          "md5": "2479947d0a9690d954666af96171375c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protos-30.1.1-javadoc.jar",
          "url": "protos-30.1.1-javadoc.jar",
          "size": 8849124,
          "sha512": "d73b863d1fb196dced2262d06027c4c4d17581653cc7612fd4b228a89ee860e63dfc6c185aec406ce5b6e67429ed5ed749b00f698e1267b3b84045646af8f057",
          "sha256": "2262aa0f22510203c2a07c1373b2574ccf594ef2158cf68a2def187ea4216cbe",
          "sha1": "09ee138e930b2db6324f6480ae8db9172db32d9f",
          "md5": "141d7acdb962568ba0454de9a6f511de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protos-30.1.1-sources.jar",
          "url": "protos-30.1.1-sources.jar",
          "size": 2141174,
          "sha512": "8a93109527db870811025f0efe9e9136cc5653a49840a8b95eab6368d7cad7f5834c0c2379eaa745d3926fd2333bce61907992d76a9629e85b842993bafd7b9d",
          "sha256": "b1f297a6e071ab613dfc610b59e2dcf7b00aaf084392196f229db37ea4565537",
          "sha1": "50e25040994556eaabf66c071863200e437dfe1a",
          "md5": "af6fbbe99284a484af6b1f1efad4752c"
        }
      ]
    }
  ]
}
