{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-coverage-proto",
    "version": "30.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.2.2.jar",
          "url": "android-test-plugin-host-coverage-proto-30.2.2.jar",
          "size": 23204,
          "sha512": "dbb2a2e2edec6e00bebdb890e6dc78bc71c8d23796f85972ab4badadac75aaa59739c61f12f196101ee44f9938e8c96faa3a6bf179670bbc057ba4b3411f206c",
          "sha256": "00dab33f9b1aa13cb654a45bf47363a157f90a43f54ab3e5dd0aa4a21d3120d8",
          "sha1": "b58f7510d5da7fe2889c93b04ff3cbe65716a355",
          "md5": "44fea9a7bc4b8e2a06067d631523fb48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.2.2.jar",
          "url": "android-test-plugin-host-coverage-proto-30.2.2.jar",
          "size": 23204,
          "sha512": "dbb2a2e2edec6e00bebdb890e6dc78bc71c8d23796f85972ab4badadac75aaa59739c61f12f196101ee44f9938e8c96faa3a6bf179670bbc057ba4b3411f206c",
          "sha256": "00dab33f9b1aa13cb654a45bf47363a157f90a43f54ab3e5dd0aa4a21d3120d8",
          "sha1": "b58f7510d5da7fe2889c93b04ff3cbe65716a355",
          "md5": "44fea9a7bc4b8e2a06067d631523fb48"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.2.2-javadoc.jar",
          "url": "android-test-plugin-host-coverage-proto-30.2.2-javadoc.jar",
          "size": 425608,
          "sha512": "7ef459c081a6367a465f4af219695fdc8ca9c45038cff30c04f85bc58593dfedcd05844d881cd373a0e24a957b6c910a772b6572f97c3c0943fae9ddd98cfa6b",
          "sha256": "f4b741c7963f4fe70e39a450a30ddb15eae15a9bb256a2d9c81e43473e5e1224",
          "sha1": "6e67f79e0e7bfdc3603484ca1114be54aff64da7",
          "md5": "60464b89ccf52e3e6b5be507b442314f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.2.2-sources.jar",
          "url": "android-test-plugin-host-coverage-proto-30.2.2-sources.jar",
          "size": 11274,
          "sha512": "976a34a0e62fd555f4bb38de11dd0faacf17d1f0986d51733b46b34878971dc355a296871a3d33f59ec2c524a45fe76cf6f34f1fc66e51385356fc83a3cea307",
          "sha256": "7321d3f9d6ab2e07d4b91b3b39d9b6d24227e044a46de5feaf94c53a04c8e6e7",
          "sha1": "83898f81cbf5815b204fc155f54569857363edb6",
          "md5": "2bdeeae9f2336a62eca233040512ed00"
        }
      ]
    }
  ]
}
